### ISSUE TITLE
Markeds-ID tilbage i URL'en på spiller-sider?

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#109]
For at spare plads i brugerfladen på spillersiden har jeg slettet markeds-id'et. Det ville dog måske være brugbart i visse situationer, at spillerne (eller deres lærer), kunne se ID'et et sted på spillersiden. Én mulighed ville være at vise markeds-id'et i URL'en, hvor der er masser af plads. 

Der skal ændres rigtig mange steder i koden for at realisere dette, men måske kan det gøres relativt hurtigt med noget forsigtigt søg-og-erstat.

**Comment by dybber** [comment]
Do it!

**Comment by dybber** [comment]
Erstattes af #134. Jeg lukker denne.
