### ISSUE TITLE
Layout af meget data på monitor og spillerside. Anden type tabs til grafer? Fjern tabeller med rå data?

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/Markedsspillet#115]
Feedback til både monitor og spillerside:

Jeg er ikke så vild med at alt data er skjult by default, da det ikke er åbenlyst at man skal klikke på overskrifterne for at se graferne fx. Måske er det mere åbenlyst med en slags tabs som fx https://getbootstrap.com/docs/5.0/components/navs-tabs/#tabs - Jeg bliver også lidt træt af animationen når man skifter mellem to grafer, og at man ikke kan se mere end én graf ad gangen... det kan være vi lige skal stå ved et whiteboard og se på mulighederne. Det kan også være vi må vælge nogle ting fra der bare ikke skal vises længere (fx de fleste tabeller)

**Comment by KristianMSchmidt** [comment]
God idé at snakke om det ved en tavle. 

Vi bør også tænke et par skridt frem, så vores design ikke skal ændres igen, hvis vi gerne vil have en udgave af spillet, hvor mange runder skal kunne afvikles hurtigt via algoritmer. Her kan det blive lidt tungt, hvis hele siden inklusiv bootstrap, jquery og alle graferne skal loades i hver runde.

**Comment by KristianMSchmidt** [comment]
Jeg tror vi kan lukke denne. Hvis noget skal ændres i layoutet, kan vi oprette nye, mere præcise issues.
