### ISSUE TITLE
Ny terminologi for "Game over"?

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#123]
"Game over" har, i hvert fald for mig, negative konnotationer - som i, at man har tabt eller er død. "Spillet er slut" eller "spillet er fuldendt" vil være bedre, tror jeg.

**Comment by dybber** [comment]
Enig. "Spillet er slut" / "The game is over" er meget bedre.

**Comment by KristianMSchmidt** [comment]
closed with pull request
