### ISSUE TITLE
Øvre grænse på "max rounds" i endelige spil?

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#127]
Hvis man prøver at skabe et spil med f.eks. 100.000 runder, så loader monitor-siden meget langsomt, selv uden handlende i spillet. Dette skyldes, tror jeg, at x-aksen i graferne helt fra starten af vises med alle runder i endelige spil. Men kunne selvfølgelig ændre dette, men problemet ville jo så bare opstå senere, hvis nogen virkelig gad spille 100.000 runder... 

Hurtig løsning: Jeg synes ikke, vi skal tillade skabelsen af spil, hvor max_rounds er valgt åndssvagt stort. Jeg ved ikke lige, hvad en rimelig grænse er - måske 500 eller 1000? Hvis der er 25 spillere er det allerede en betragtelig mængde data, som skal genereres til grafer i de sidste runder. Måske skal tallet være endnu lavere, for hvem ville i den virkelige verden spille mere end f.eks. 100 runder?

Hvis vi får lavet en version af spillet, hvor der er algoritmiske agenter, så bør vi nok også stoppe selv uendelige spil efter et vist antal runder. Men det kan vi tage til den tid...

**Comment by dybber** [comment]
Ja, et maximum er fint. Max på 100 runder ved spil som de er nu er også fint. Så må vi tage stilling til hvordan det skal være hvis vi indfører algoritmiske agenter.
