### ISSUE TITLE
Update Danish translations before a more final release

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/Markedsspillet#172]

**Comment by KristianMSchmidt** [comment]
Translation of emails should also be checked.

**Comment by KristianMSchmidt** [comment]
... and we should not forget to translate (or check the translation of ...) the all-auth messages (generated after login, logout ect. ). The messages are available here: 
https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account/messages

**Comment by KristianMSchmidt** [comment]
Oversættelsesspørgsmål: 

- "spiller" vs "forhandler".
- "You made a trade!" og "Make trade"
-
