### ISSUE TITLE
Front page: Don't show buttons that require login

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/Markedsspillet#182]
I think the "Host a new market" section should be different on the frontpage depending on whether a user has logged in or not.

Right now new users can click "Opret nyt marked", without being logged in, being redirected to a login form. From there new users have to find the tiny "Opret en bruger" button in the bottom of the login form.

I think it would make more sense if there was an easily accessible "Opret en bruger" button already on the front page.

We could perhaps look at what other websites are doing design wise these days...

**Comment by KristianMSchmidt** [comment]
Let's make a drawing of the front page we want on the white board next Wednesday. Once we have agreed on layout and content, the implementation shouldn't be difficult.

**Comment by dybber** [comment]
Deal. One drawing for both logged in and not logged in.
