### ISSUE TITLE
Småting

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/Markedsspillet#195]
Spillerside:
 - "Dine produktionstal" som overskrift
 - Overskrift på balance chart
 - Ændr maxpris til 4x max produktionspris
 - kr. på mellemregninger
 - første runde: tilføj teksten "Dine faste produktionsomkostninger er 8 kr."
 - grafen på produktionsomkostninger skal forlænges til alle runderne

**Comment by KristianMSchmidt** [comment]
Hjemmeside:
Udfyld navnefelt i form med spillernavn i session når et sådant findes
