### ISSUE TITLE
What to do with robots/algorithms when game is endless?

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#208]
should robots be allowed in endless games? should they stop after a certain number of rounds?

**Comment by dybber** [comment]
Perhaps all endless games should have an "End the game" button in the monitor view? Perhaps also a Pause button would be nice for all types of games?

**Comment by KristianMSchmidt** [comment]
An "End the game" or "Make this the last round"-button on the monitor page is a good idea.
