### ISSUE TITLE
Ability to become bankrupt after a round

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/Markedsspillet#25]

**Comment by dybber** [comment]
I think we should wait until we've talked with Niels about this, and I have thus removed it from the beta1 milestone

**Comment by KristianMSchmidt** [comment]
This issue is closely related to issue #62

**Comment by dybber** [comment]
We've talked with Niels, and the solution is now outlined in #168. I will thus close this issue and we can continue discussing it in the new issue.
