### ISSUE TITLE
Decide/Read up on reasonable input values for alpha, beta and theta and implement form validation for these fields in MarketForm

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#47]

**Comment by dybber** [comment]
Link to #165

**Comment by dybber** [comment]
Som jeg læser Niels seneste email, så skal vi droppe yderligere constraints, da han synes det giver mening at lærerne også kan eksperimentere med variabler der ikke giver mening. Så jeg lukker.
