### ISSUE TITLE
Show unit production costs and last round market avg. price on sliders in participants view 

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#69]

**Comment by KristianMSchmidt** [comment]
I think it will require some work to get this done properly, but here is some inspiration (and key words for further google search):
https://stackoverflow.com/questions/26612700/ticks-for-type-range-html-input

**Comment by dybber** [comment]
Great find! This answer looks neat: https://stackoverflow.com/a/64306268/496605
if you look at this demo it links to: https://codepen.io/vsync/pen/mdEJMLv

I can take a look at integrating that CSS/JS, if you want to

**Comment by KristianMSchmidt** [comment]
Sure, give it a go!

**Comment by dybber** [comment]
I have looked at this and it's non-trivial. I will thus mark this as nice to have, as it requires some CSS expertise that we don't have.

It might be possible with somekind of UI toolkit, like Material UI. See for instance: https://material-ui.com/components/slider/#custom-marks However, doing it directly with CSS/JS seems to be too huge an undertaking.

**Comment by dybber** [comment]
I think it works well as it is. It will be too involved to move to Material UI instead of bootstrap IMO. I will close this.

**Comment by dybber** [comment]
I'll try working at it again using https://github.com/IonDen/ion.rangeSlider
