### ISSUE TITLE
Sign up (for hosts) should be possible with email & password only

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#71]
The default django solution with username, email and password is a bit dated. And the username is not used for anything and is thus easy to forget.  Email and password only would be better.
 
The easiest way to achieve the above is probably to install the very popular 3rd party app 'django-allauth' and choose the right settings for this.

**Comment by KristianMSchmidt** [comment]
If we keep the current implementation we should imo at least make the email field in the sign up form mandatory. Without the email users who forget their username will not be able to access their account again.

**Comment by dybber** [comment]
Hej Kristian. Vil du ikke kigge på hvor svært det er at lave denne ændring? Hvis det er bøvlet, så dropper vi det, hvis det er nemt så synes jeg vi skal gøre det.

**Comment by KristianMSchmidt** [comment]
Jo, det kan jeg kigge på næste onsdag. Jeg tror ikke, det er svært. Men måske kræver det, at vi genskaber databasen fra scratch og sletter alle migrations.

**Comment by dybber** [comment]
Super, der er vist ikke noget af værdi i databasen alligevel.
