### ISSUE TITLE
Either re-implement or remove "download statistics" feature and button  

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#73]
Perhaps we should ask Niels if this in an important feature. It probably depends on what graphs and tables we end up showing in the monitor and player interfaces

**Comment by KristianMSchmidt** [comment]
Knappen er skjult. Skal vi ikke bare lukke dette issue - og så genåbne et nyt issue, hvis Niels ønsker en download feature?

**Comment by dybber** [comment]
Det kan vi godt!
