### ISSUE TITLE
Decide on one (perhaps two) additional default market settings

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/Markedsspillet#93]
Currently there are two options: 'baguette' and 'wedding cake'. The settings for baguette are from the article and work just fine. However, the settings for wedding cake are somewhat arbitrary at the moment and will probably not work so well in practice. Perhaps we should assign this issue til Niels.

**Comment by dybber** [comment]
Yes, we agreed that Niels would prepare some of these defaults.
